# Generated by Django 5.1.1 on 2024-10-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_date_joined_alter_usuario_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(help_text='Please enter a valid email address.', max_length=254, verbose_name='email address'),
        ),
    ]
