# Generated by Django 5.1.1 on 2024-10-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='name_prod',
            field=models.CharField(default='No Aplica', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='price_prod',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_prod',
            field=models.IntegerField(),
        ),
    ]
